project:
  type: book
  output-dir: docs

book:
  title: "Bae-note"
  author: "Shafayet"
  date: last-modified
  date-format: long
  chapters:
    - index.qmd
    - ch06-approx-posterior.qmd
    - ch06-soln.qmd
    - ch08-posterior-inference.qmd
    - ch09-simple-normal-reg.qmd


format:
  html:
    theme: cosmo
execute: 
  warning: false

